title: Chief Cosmic's Charismatic Code Collection!
author: Anmol_Tomer_CC
email: anmol3540@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Computer Science Blog with posts on topics such as IT, Cloud Computing and Web Services, Computer Science Engineering, 
  Algorithms, Cybersecurity, Networking, Data Science, Machine Learning and Artificial Intelligence.

# social links
twitter_username: https://twitter.com/t_anmol_t
github_username:  https://github.com/AnmolTomer

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
